### ISSUE TITLE
Suggestion : écouter sur l'IP publique directement

### ISSUE THREAD

**Issue by Wonderfall** [hardware/nsd-dnssec#15]
Actuellement le conteneur écoute sur tout alors que ce serait plus intéressant de mettre directement l'IP publique, du style : 

```
  ports:
    - "IP_PUBLIQUE:53:53"
    - "IP_PUBLIQUE:53:53/udp"
```

Pour la simple et bonne raison que si on veut mettre en place un résolveur DNS local comme Unbound par exemple, on serait bien embêté avec la configuration proposée par le README.

Je suggère donc de modifier le README et l'exemple du `docker-compose.yml`, mais avant de le faire je te demande si tu trouves que c'est une bonne chose à faire.

**Comment by hardware** [comment]
Oui je suis d'accord, je te laisse faire la modification :)

Mais faudra préciser que c'est dans le cas où on veut éviter un conflit avec un serveur de type récursif comme Unbound qui tourne en parallèle.

**Comment by Wonderfall** [comment]
Je me suis pas cassé la tête : https://github.com/hardware/nsd-dnssec/commit/b17e577fe70eb2c87777234b0b4fb775af2e9d24
Mais si tu veux que j'explique plus je peux refaire le commit, sinon tu peux close l'issue. ;)
