### ISSUE TITLE
SSL issue with nlalpinelinux.org

### ISSUE THREAD

**Issue by timwhite** [hardware/nsd-dnssec#26]
It appears that https://nl.alpinelinux.org/alpine/v3.7/community only has a SSL certificate for nl3.alpinelinux.org. Updating it to nl3 allows me to build it. Not sure why that change has occured.

**Comment by michael-k** [comment]
This is related to alpine and not to this image.  I reported it in alpine's bug tracker: https://bugs.alpinelinux.org/issues/9056

**Comment by michael-k** [comment]
Certificate has been updated.

@timwhite can you please close the issue?
